In [21]:
import pandas as pd
df= pd.read_csv('orders.csv',na_values =['Not Available', 'Unknown'])
df.head(30)
df['Customer Status'].unique()

Index(['Customer ID', 'Customer Status', 'Date Order was placed',
       'Delivery Date', 'Order ID', 'Product ID', 'Quantity Ordered',
       'Total Retail Price for This Order', 'Cost Price Per Unit'],
      dtype='object')

In [2]:
df.rename(columns={'Customer ID':'customer_id', 'Customer Status':'customer_status'})

,customer_id,customer_status,Date Order was placed,Delivery Date,Order ID,Product ID,Quantity Ordered,Total Retail Price for This Order,Cost Price Per Unit
0,579,Silver,01-Jan-17,07-Jan-17,123002578,2.201010e+11,2,92.6,20.70
1,7574,SILVER,01-Jan-17,05-Jan-17,123004074,2.102010e+11,1,21.7,9.95
2,28861,NaN,01-Jan-17,04-Jan-17,123000871,2.301010e+11,1,1.7,0.80
3,43796,Gold,01-Jan-17,06-Jan-17,123002851,2.201000e+11,1,47.9,24.05
4,54673,Gold,01-Jan-17,04-Jan-17,123003607,2.202000e+11,1,36.9,18.30
...,...,...,...,...,...,...,...,...,...
185008,92467,SILVER,31-Dec-21,31-Dec-21,124433239,2.401000e+11,4,64.0,6.35
185009,92866,Silver,31-Dec-21,31-Dec-21,124436561,2.301010e+11,1,16.7,7.25
185010,92894,Silver,31-Dec-21,31-Dec-21,124434316,2.202000e+11,5,313.0,31.40
185011,93239,Gold,31-Dec-21,02-Jan-22,124436170,2.202000e+11,2,271.6,68.00
185012,93317,Silver,31-Dec-21,31-Dec-21,124434324,2.201010e+11,4,95.6,10.95

In [3]:
df.columns = df.columns.str.replace(' ','_')
df.head(10)

,Customer_ID,Customer_Status,Date_Order_was_placed,Delivery_Date,Order_ID,Product_ID,Quantity_Ordered,Total_Retail_Price_for_This_Order,Cost_Price_Per_Unit
0,579,Silver,01-Jan-17,07-Jan-17,123002578,2.201010e+11,2,92.6,20.70
1,7574,SILVER,01-Jan-17,05-Jan-17,123004074,2.102010e+11,1,21.7,9.95
2,28861,NaN,01-Jan-17,04-Jan-17,123000871,2.301010e+11,1,1.7,0.80
3,43796,Gold,01-Jan-17,06-Jan-17,123002851,2.201000e+11,1,47.9,24.05
4,54673,Gold,01-Jan-17,04-Jan-17,123003607,2.202000e+11,1,36.9,18.30
5,74503,Silver,01-Jan-17,04-Jan-17,123000487,2.402000e+11,1,24.7,11.80
6,1870,NaN,02-Jan-17,02-Jan-17,123006324,2.401000e+11,1,65.5,25.60
7,2351,Silver,02-Jan-17,02-Jan-17,123005769,2.406000e+11,2,44.0,9.10
8,3073,Silver,02-Jan-17,02-Jan-17,123008467,2.402000e+11,1,108.7,56.30
9,5907,Gold,02-Jan-17,06-Jan-17,123008924,2.202000e+11,1,53.0,26.60

In [4]:
df.columns = df.columns.str.lower()
df.head(10)

,customer_id,customer_status,date_order_was_placed,delivery_date,order_id,product_id,quantity_ordered,total_retail_price_for_this_order,cost_price_per_unit
0,579,Silver,01-Jan-17,07-Jan-17,123002578,2.201010e+11,2,92.6,20.70
1,7574,SILVER,01-Jan-17,05-Jan-17,123004074,2.102010e+11,1,21.7,9.95
2,28861,NaN,01-Jan-17,04-Jan-17,123000871,2.301010e+11,1,1.7,0.80
3,43796,Gold,01-Jan-17,06-Jan-17,123002851,2.201000e+11,1,47.9,24.05
4,54673,Gold,01-Jan-17,04-Jan-17,123003607,2.202000e+11,1,36.9,18.30
5,74503,Silver,01-Jan-17,04-Jan-17,123000487,2.402000e+11,1,24.7,11.80
6,1870,NaN,02-Jan-17,02-Jan-17,123006324,2.401000e+11,1,65.5,25.60
7,2351,Silver,02-Jan-17,02-Jan-17,123005769,2.406000e+11,2,44.0,9.10
8,3073,Silver,02-Jan-17,02-Jan-17,123008467,2.402000e+11,1,108.7,56.30
9,5907,Gold,02-Jan-17,06-Jan-17,123008924,2.202000e+11,1,53.0,26.60

In [5]:
df['total_cost_price'] = df['cost_price_per_unit'] * df['quantity_ordered']
df.head(10)

,customer_id,customer_status,date_order_was_placed,delivery_date,order_id,product_id,quantity_ordered,total_retail_price_for_this_order,cost_price_per_unit,total_cost_price
0,579,Silver,01-Jan-17,07-Jan-17,123002578,2.201010e+11,2,92.6,20.70,41.40
1,7574,SILVER,01-Jan-17,05-Jan-17,123004074,2.102010e+11,1,21.7,9.95,9.95
2,28861,NaN,01-Jan-17,04-Jan-17,123000871,2.301010e+11,1,1.7,0.80,0.80
3,43796,Gold,01-Jan-17,06-Jan-17,123002851,2.201000e+11,1,47.9,24.05,24.05
4,54673,Gold,01-Jan-17,04-Jan-17,123003607,2.202000e+11,1,36.9,18.30,18.30
5,74503,Silver,01-Jan-17,04-Jan-17,123000487,2.402000e+11,1,24.7,11.80,11.80
6,1870,NaN,02-Jan-17,02-Jan-17,123006324,2.401000e+11,1,65.5,25.60,25.60
7,2351,Silver,02-Jan-17,02-Jan-17,123005769,2.406000e+11,2,44.0,9.10,18.20
8,3073,Silver,02-Jan-17,02-Jan-17,123008467,2.402000e+11,1,108.7,56.30,56.30
9,5907,Gold,02-Jan-17,06-Jan-17,123008924,2.202000e+11,1,53.0,26.60,26.60

In [6]:
df['profit'] = df['total_retail_price_for_this_order'] - df['total_cost_price']
df.head(10)

,customer_id,customer_status,date_order_was_placed,delivery_date,order_id,product_id,quantity_ordered,total_retail_price_for_this_order,cost_price_per_unit,total_cost_price,profit
0,579,Silver,01-Jan-17,07-Jan-17,123002578,2.201010e+11,2,92.6,20.70,41.40,51.20
1,7574,SILVER,01-Jan-17,05-Jan-17,123004074,2.102010e+11,1,21.7,9.95,9.95,11.75
2,28861,NaN,01-Jan-17,04-Jan-17,123000871,2.301010e+11,1,1.7,0.80,0.80,0.90
3,43796,Gold,01-Jan-17,06-Jan-17,123002851,2.201000e+11,1,47.9,24.05,24.05,23.85
4,54673,Gold,01-Jan-17,04-Jan-17,123003607,2.202000e+11,1,36.9,18.30,18.30,18.60
5,74503,Silver,01-Jan-17,04-Jan-17,123000487,2.402000e+11,1,24.7,11.80,11.80,12.90
6,1870,NaN,02-Jan-17,02-Jan-17,123006324,2.401000e+11,1,65.5,25.60,25.60,39.90
7,2351,Silver,02-Jan-17,02-Jan-17,123005769,2.406000e+11,2,44.0,9.10,18.20,25.80
8,3073,Silver,02-Jan-17,02-Jan-17,123008467,2.402000e+11,1,108.7,56.30,56.30,52.40
9,5907,Gold,02-Jan-17,06-Jan-17,123008924,2.202000e+11,1,53.0,26.60,26.60,26.40

In [7]:
df['order_date'] = pd.to_datetime(df['date_order_was_placed'],format="%d-%b-%y")
df.head(10)

,customer_id,customer_status,date_order_was_placed,delivery_date,order_id,product_id,quantity_ordered,total_retail_price_for_this_order,cost_price_per_unit,total_cost_price,profit,order_date
0,579,Silver,01-Jan-17,07-Jan-17,123002578,2.201010e+11,2,92.6,20.70,41.40,51.20,2017-01-01
1,7574,SILVER,01-Jan-17,05-Jan-17,123004074,2.102010e+11,1,21.7,9.95,9.95,11.75,2017-01-01
2,28861,NaN,01-Jan-17,04-Jan-17,123000871,2.301010e+11,1,1.7,0.80,0.80,0.90,2017-01-01
3,43796,Gold,01-Jan-17,06-Jan-17,123002851,2.201000e+11,1,47.9,24.05,24.05,23.85,2017-01-01
4,54673,Gold,01-Jan-17,04-Jan-17,123003607,2.202000e+11,1,36.9,18.30,18.30,18.60,2017-01-01
5,74503,Silver,01-Jan-17,04-Jan-17,123000487,2.402000e+11,1,24.7,11.80,11.80,12.90,2017-01-01
6,1870,NaN,02-Jan-17,02-Jan-17,123006324,2.401000e+11,1,65.5,25.60,25.60,39.90,2017-01-02
7,2351,Silver,02-Jan-17,02-Jan-17,123005769,2.406000e+11,2,44.0,9.10,18.20,25.80,2017-01-02
8,3073,Silver,02-Jan-17,02-Jan-17,123008467,2.402000e+11,1,108.7,56.30,56.30,52.40,2017-01-02
9,5907,Gold,02-Jan-17,06-Jan-17,123008924,2.202000e+11,1,53.0,26.60,26.60,26.40,2017-01-02

In [8]:
df.drop(columns=['cost_price_per_unit', 'date_order_was_placed'], inplace = True)
df.head(10)

,customer_id,customer_status,delivery_date,order_id,product_id,quantity_ordered,total_retail_price_for_this_order,total_cost_price,profit,order_date
0,579,Silver,07-Jan-17,123002578,2.201010e+11,2,92.6,41.40,51.20,2017-01-01
1,7574,SILVER,05-Jan-17,123004074,2.102010e+11,1,21.7,9.95,11.75,2017-01-01
2,28861,NaN,04-Jan-17,123000871,2.301010e+11,1,1.7,0.80,0.90,2017-01-01
3,43796,Gold,06-Jan-17,123002851,2.201000e+11,1,47.9,24.05,23.85,2017-01-01
4,54673,Gold,04-Jan-17,123003607,2.202000e+11,1,36.9,18.30,18.60,2017-01-01
5,74503,Silver,04-Jan-17,123000487,2.402000e+11,1,24.7,11.80,12.90,2017-01-01
6,1870,NaN,02-Jan-17,123006324,2.401000e+11,1,65.5,25.60,39.90,2017-01-02
7,2351,Silver,02-Jan-17,123005769,2.406000e+11,2,44.0,18.20,25.80,2017-01-02
8,3073,Silver,02-Jan-17,123008467,2.402000e+11,1,108.7,56.30,52.40,2017-01-02
9,5907,Gold,06-Jan-17,123008924,2.202000e+11,1,53.0,26.60,26.40,2017-01-02

In [9]:
duplicateRows = df[df.duplicated()]
df.drop_duplicates(keep=False)
df.head(10)

,customer_id,customer_status,delivery_date,order_id,product_id,quantity_ordered,total_retail_price_for_this_order,total_cost_price,profit,order_date
0,579,Silver,07-Jan-17,123002578,2.201010e+11,2,92.6,41.40,51.20,2017-01-01
1,7574,SILVER,05-Jan-17,123004074,2.102010e+11,1,21.7,9.95,11.75,2017-01-01
2,28861,NaN,04-Jan-17,123000871,2.301010e+11,1,1.7,0.80,0.90,2017-01-01
3,43796,Gold,06-Jan-17,123002851,2.201000e+11,1,47.9,24.05,23.85,2017-01-01
4,54673,Gold,04-Jan-17,123003607,2.202000e+11,1,36.9,18.30,18.60,2017-01-01
5,74503,Silver,04-Jan-17,123000487,2.402000e+11,1,24.7,11.80,12.90,2017-01-01
6,1870,NaN,02-Jan-17,123006324,2.401000e+11,1,65.5,25.60,39.90,2017-01-02
7,2351,Silver,02-Jan-17,123005769,2.406000e+11,2,44.0,18.20,25.80,2017-01-02
8,3073,Silver,02-Jan-17,123008467,2.402000e+11,1,108.7,56.30,52.40,2017-01-02
9,5907,Gold,06-Jan-17,123008924,2.202000e+11,1,53.0,26.60,26.40,2017-01-02

In [10]:
from sqlalchemy import create_engine
import os

os.environ['MYSQL_PASSWORD'] = "12345678"
password = os.getenv('MYSQL_PASSWORD')

# Create engine and handle connection errors
engine = create_engine(f'mysql+mysqlconnector://root:{password}@localhost/testDB',
            connect_args={'auth_plugin': 'caching_sha2_password'})
print(f"Mysql is connected successfully with create_engine: {engine}")
df.to_sql('orders', engine, if_exists ='replace', index=False)

Mysql is connected successfully with create_engine: Engine(mysql+mysqlconnector://root:***@localhost/testDB)

185013

In [13]:
# Find top 10 highest sales along with the customer IDs.

query = """
    SELECT customer_id, sum(total_retail_price_for_this_order) AS sales
    FROM orders
    GROUP BY customer_id
    ORDER BY sales DESC
    LIMIT 10;
"""

df = pd.read_sql(query, engine)
df.head(30)

   customer_id   sales
0         7766  6826.3
1        31519  6585.8
2        77062  6569.6
3        89591  6432.5
4        54290  6382.0
5        28530  6257.2
6        53078  5027.4
7        92062  5016.3
8        62745  4991.3
9         3190  4893.1

In [15]:
# Find month over month growth comparison for 2020 and 2021 sales, e.g., Jan. 2020 vs Jan. 2021
query = """
    WITH CTE1 AS
        (SELECT DISTINCT year(order_date) AS order_year, month(order_date) AS
            order_month, sum(total_retail_price_for_this_order) AS sales
            FROM orders
            GROUP BY year(order_date), month(order_date)
            ORDER BY year(order_date), month(order_date)
        )
    SELECT CTE1.order_month,
        sum(CASE WHEN CTE1.order_year = 2020 THEN sales ELSE 0 END) AS sales_2020,
        sum(CASE WHEN CTE1.order_year = 2021 THEN sales ELSE 0 END) AS sales_2021
        FROM CTE1
        GROUP BY CTE1.order_month
        ORDER BY CTE1.order_month;
"""

df = pd.read_sql(query, engine)

df.head(30)

    order_month  sales_2020  sales_2021
0             1  363965.360  422961.345
1             2  305807.600  336529.265
2             3  276046.080  279331.885
3             4  403484.095  454806.345
4             5  462698.175  512668.840
5             6  577972.750  642173.510
6             7  581496.045  664787.095
7             8  562614.130  658272.605
8             9  251785.210  313872.490
9            10  268368.005  328082.135
10           11  304962.640  392866.005
11           12  625615.845  930156.135

In [22]:
df= pd.read_csv('sales_teams.csv',na_values =['Not Available', 'Unknown'])
print(df.columns)

Index(['Sales Agent', 'Manager', 'Regional Office'], dtype='object')

In [23]:
df= pd.read_csv('sales.csv',na_values =['Not Available', 'Unknown'])
print(df.columns)

Index(['Sales ID', 'Sales Agent', 'Product Name', 'Account', 'Deal Stage',
       'Deal Engage Date', 'Deal Close Date', 'Close Value Per Unit',
       'Closing Quantity'],
      dtype='object')